---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: APP_NAME
  namespace: APP_NAME-system
  labels:
    app: APP_NAME
spec:
  replicas: 3
  selector:
    matchLabels:
      app: APP_NAME
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
        - name: APP_NAME
          image: DOCKERHUB_USERNAME/APP_NAME:GIT_HASH
          env:
          - name: META_TITLE
            value: "Teo's Cloud"
          - name: META_DESCRIPTION
            value: "Teo's Cloud"
          - name: META_AUTHOR
            value: "Mateo Ortegon"
          - name: LANG
            value: "en"
          - name: THEME
            value: "Dark"
          - name: FAVICON_URL
            value: "https://olc-wordpress-assets.s3.amazonaws.com/uploads/2020/05/cloud-icon.png"
          - name: AVATAR_URL
            value: "https://miro.medium.com/fit/c/1360/1360/0*p7du7PBJUO4wnQBQ."
          - name: AVATAR_2X_URL
            value: "https://miro.medium.com/fit/c/1360/1360/0*p7du7PBJUO4wnQBQ."
          - name: AVATAR_ALT
            value: "https://miro.medium.com/fit/c/1360/1360/0*p7du7PBJUO4wnQBQ."
          - name: NAME
            value: "Mateo Ortegon"
          - name: BIO
            value: "Hey! This is a list of links to workloads running on this HA K3s cluster as well as some Social media links. \n Source on GitHub below."
          - name: FOOTER
            value: "Thanks for stopping by! : )"
          - name: GITHUB
            value: "https://github.com/teoo-io"
          - name: LINKED_IN
            value: "https://www.linkedin.com/in/mateoortegon"
          - name: BUTTON_ORDER
            value: "RANCHER,NES,DOCS,GITHUB,LINKED_IN,EMAIL"
          - name: CUSTOM_BUTTON_TEXT
            value: "Rancher K3s,NES Emulator,Docs + Guides, E-mail"
          - name: CUSTOM_BUTTON_URL
            value: "https://rancher.teoo.io,https://nes.teoo.io,https://docs.teoo.io,mailto:m@teoo.io"
          - name: CUSTOM_BUTTON_COLOR
            value: "#30BA78,#ED2756,#0085FF,#99A3A8"
          - name: CUSTOM_BUTTON_TEXT_COLOR
            value: "#ffffff,#ffffff","#ffffff","#ffffff"
          - name: CUSTOM_BUTTON_ALT_TEXT
            value: "Rancher Dashboard,PLay Nintendo,Documentation Archive,E-mail me!"
          - name: CUSTOM_BUTTON_NAME
            value: "RANCHER,NES,DOCS,EMAIL"
          - name: CUSTOM_BUTTON_ICON
            value: "fas cubes,fas-books"
          ports:
            - name: APP_NAME-svc
              containerPort: 3000
